### ISSUE TITLE
Lack of ingame oriented logs

### ISSUE THREAD

**Issue by danieldomanski** [OpenSourceLAN/srcds-log-receiver#2]
Hello,

I am running SRCDS on a VM (Ubuntu 14.04) and connecting to csgo server via Windows client on the same machine. Server uses the newest WarMod release, and is correctly logging what happened in-game, e.g: 

` 07/26/2017 - 15:40:02: [WarMod_BFG] {"timestamp": "2017-07-26 15:40:02", "event": "item_pickup", "round": 1, "player": {"name": "Ethan", "userId": 7, "uniqueId": "BOT", "team": 3, "origin": {"x": -1598.00, "y": -1732.00, "z": -204.22}, "velocity": {"x": 0.00, "y": 0.00, "z": 0.00}, "view": {"x": 0.00, "y": 106.00, "z": 0.00}, "health": 100, "armor": 0, "helmet": 0}, "item": "knife"}`

`L 07/26/2017 - 15:40:02: [WarMod_BFG] {"timestamp": "2017-07-26 15:40:02", "event": "item_pickup", "round": 1, "player": {"name": "Ethan", "userId": 7, "uniqueId": "BOT", "team": 3, "origin": {"x": -1598.00, "y": -1732.00, "z": -204.22}, "velocity": {"x": 0.00, "y": 0.00, "z": 0.00}, "view": {"x": 0.00, "y": 106.00, "z": 0.00}, "health": 100, "armor": 0, "helmet": 0}, "item": "hkp2000"}`

My issue is that I cannot receive any ingame-oriented logs like that in my script. Instead, I get bunch of  cvar server settings logs, like for example when changing map, or when I put "log on" it also is visible via .js script console. This is how it looks like: 

![Console](https://image.ibb.co/gad2Uk/console2.png)

I'm struggling with that because getting that in-game data flow into my .js script is crucial. I know I can take the log files and parse them into .json objects, but that's the last ultimate choice. Key question might be: Is it even possible to get that data with ur module/ via UDP protocol, and then break it down to .json objects?
What I tried to do:
* ofc setting all the commands in server console:
`log "on" 
sv_rcon_log "1" 
sv_logfile "0" 
sv_logecho "1" 
sv_log_onefile "0"
sv_logbans "1" 
mp_logdetail "3"`
* seting all WarMode related commands to enable logging 
`wm_stats_enabled 1
 wm_stats_method 2
wm_stats_trace 1`
* I tried to figure out if it can be problem with WarMode, so I permamently disabled all SourceMod plugins, and SourceMod itself
* via log_dumpchannels tried different flag combination on distinctive channels

Everything made no difference. Any kind of help would be appreciated.

Cheers!

**Comment by sirsquidness** [comment]
Howdy!

So just to make sure I understand your problem...

* You have CS server running warmod
* You have set up a custom app using the srcds log receiver
* When the app is configured to send logs to the app, you only get console messages

So from this, because you have the console messages, we know that the network is working and you have added the correct address with `logaddress_add`. I think there are two paths to investigate

* can you verify that the logaddress remains configured? In your srcds console, do `logaddress_list` and verify that the destination still exists
* Run the [save to disk](https://github.com/OpenSourceLAN/srcds-log-receiver/blob/master/saveToDisk.ts) example app instead of your custom one to see if there is some logic in your app that is hiding the messages

If the first suggestion does not show the address, you should search your configuration for any `logaddress` cvars - there might be a `logaddress_delall`.

If the second suggestion shows up the correct log messages, I can take a look at the code you've written to see if I can spot the error.

Let me know how you go! )

**Comment by danieldomanski** [comment]
Hi!

I don't know what kind of magic u did, but everything seems to be working now and I am getting correct logs that fully satisfy me:) 

The funny part is that yesterday somehow, my virtual machine got some weird black screen a while after boot and I couldnt do anything, so I restored the state to some 2week-old snapshot. I had to do all the metamod, sourcemod, warmod installing thing one more time and just after trying to get some console logs through my .js app everything's started to work properly!

Thank you for your kind and helpful response.
I really appreciate ur great work, thanks for sharing.

Cheers!
